event_inherited();
can_corpse = false;
image_speed = 0.5;
size = 128;
my_health = 500;
kick = 0;
spridle = sprHelicopter;
sprdead = sprHelicopterDeath;
sprfire = sprHelicopterFire;
sprhurt = sprHelicopterHit;
my_dsound = sndHeliExplo;
my_hsound = sndEnemy1Hit;
myangle = Player.angle;
emitter = sound_emitter(x, y, z);
heli = sound_loop(sndHelicopter, emitter);
sound_volume(heli, 0);
vol = 0;
up = 1;
mode = 0;
myz = -160;
myturn = choose(1, -1);
alarm[1] = 300;
fire = 0;
sound_play(choose(sndBossGreet1, sndBossGreet2, sndBossGreet3));
