window_mouse_set(window_get_width() / 2, window_get_height() / 2);
angle = 90;
angle_v = 0;
walk = 0;
fog = 1; // 100%
hdr = 320;
guny = 0;
minigun = 0;
dead = 0;
deadtime = 0;
win = 0;
wintime = 0;
tilt = 0;
stars = 0;
z = 16;
gunanim = 0;
can_shoot = true;
starz = 0;
my_health = 100;
maxhp = 100;
wep = UberCont.p_gun;
knifewep = Weapons.Pistol;
nextwep = 0;
weapons = array_create(Weapons.Length, 0);
ammo = array_create(Weapons.Length, 0);
scrWeps();
red = 0;
hitx = x;
hity = y;
playerIndex = 0;
zspeed = 0;
walkspeed = 1;
shootemt = sound_emitter(x, y, z);
shootbus = sound_bus();
var ef_reverb = audio_effect_create(AudioEffectType.Reverb1);
ef_reverb.size = 0.6;
ef_reverb.mix = 0.5;
shootbus.effects[0] = ef_reverb;
sound_emitter_bus(shootemt, shootbus);

no_mlock = false;